### PR TITLE
scs:bugfix - att outdated chsharp sdk on horusec-engine-csharp

### LINKED ISSUE #1021: bug: security code scan - invalid character 'C' looking for beginning of value
**What happened**: When i run the analysis on the cake [repository](https://github.com/cake-build/cake) i get the followed result:
```

time="2022-03-09T15:06:38-03:00" level=warning msg="[HORUSEC] 62 VULNERABILITIES WERE FOUND IN YOUR CODE SENT TO HORUSEC, TO SEE MORE DETAILS USE THE LOG LEVEL AS DEBUG AND TRY AGAIN"

time="2022-03-09T15:06:38-03:00" level=warning msg="{HORUSEC_CLI} Horusec not show info vulnerabilities in this analysis, to see info vulnerabilities add option \"--information-severity=true\". For more details use (horusec start --help) command."

==================================================================================

time="2022-03-09T15:06:38-03:00" level=warning msg="{HORUSEC_CLI} During execution we found some problems:"

time="2022-03-09T15:06:38-03:00" level=error msg="invalid character 'C' looking for beginning of value"

```
when running in debug level i could check the following error:

`time="2022-03-09T15:06:32-03:00" level=debug msg="{HORUSEC_CLI} Something error went wrong in SecurityCodeScan tool | analysisID -> 3e30a57a-164d-4e36-8bd1-5a89d29939f9 | output ->  - invalid character 'C' looking for beginning of value"`

**What you expected to happen**: 
Receive no error when i run horusec in cake repository

**How to reproduce it (as minimally and precisely as possible)**:

`git clone https://github.com/cake-build/cake.git`

`horusec start  -p .`

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`):  make build-install-cli-linux on branch v2.8
- Operating System: ubuntu 20.04

### PR DESCRIPTION
**Pull request by iancardosozup**
fixes #1021
Signed-off-by: Ian Cardoso <ian.cardoso@zup.com.br>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by nathanmartinszup — APPROVED** [review]

File: internal/services/formatters/csharp/scs/formatter.go [hunk 1]
```diff
@@ -41,12 +41,19 @@ var (
...
+	ErrInvalidSDKOutput = errors.New("horusec-engine-csharp SDK is outdated, " +
+		"you can build your own and add to horusecCliCustomImages config" +
+		" or create a new issue on https://github.com/ZupIT/horusec/issues to maintainers update the image")
 )
 
 const (
 	BuildFailedOutput    = "Msbuild failed when processing the file"
 	SolutionFileNotFound = "solution file not found"
 	solutionExt          = ".sln"
+	InvalidSDKOutput     = "Could not execute because the application was not found or a " +
```
Comment (matheusalcantarazup) [inline internal/services/formatters/csharp/scs/formatter.go:55]: Why this should be public?

**Review by matheusalcantarazup — CHANGES_REQUESTED** [review]

**Review by matheusalcantarazup — APPROVED** [review]
