### PR TITLE
engines/jvm:fix - false positives on base64 encode/decode

### LINKED ISSUE #816: False positive when dealing with basic authentication's and Base64 encoding
**What happened**:
Horusec reports that this code:

```java
Code .addContentType("application/x-www-form-urlencoded")
```
as: **Basic authentication's only means of obfuscation is Base64 encoding. Since Base64 encoding is easily recognized and reversed, it offers only the thinnest veil of protection to your users, and should not be used.**

Maybe I'm wrong but, why is this a base64 security issue?

**What you expected to happen**:

Not be reported as a vulnerability.

**How to reproduce it (as minimally and precisely as possible)**:

Create a minimal kotlin project that make a http request with the `Content-Type` header set as `application/x-www-form-urlencoded`

**Environment**:
- Horusec version (use `horusec version`):  v1.10.3
- Operating System: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by matheusalcantarazup**
Previously the rules of encode/decode Base64 was reporting any string
that had the value encode/decode which was generating a lot of false
positive. This commit improve the regex of these rules to catch only
the method call that match encode or decode on name.

The type of rule HS-JVM-24 was changed from AndMatch to OrMatch to
follow the same behaviour of HS-JVM-28.

Fixes #816

Signed-off-by: Matheus Alcantara <matheus.alcantara@zup.com.br>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

File: internal/services/engines/jvm/samples_test.go [hunk 1]
```diff
@@ -13,3 +13,46 @@
...
+class T {
+	void f() {
+		this.decodeSomeRandomValue("value);
+		console.log.println("foo.decode");
+	}
+
+	void decodeSomeRandomValue(String value) {}
+}
+`
+)
```
Comment (matheusalcantarazup) [inline internal/services/engines/jvm/samples_test.go:58]: I'm not that creative to write better examples, I welcome suggestions.

Comment (iancardosozup) [reply internal/services/engines/jvm/samples_test.go:58]: we could use some examples mentioned on #816 , most of them was on .xml and .gradle files

Comment (matheusalcantarazup) [reply internal/services/engines/jvm/samples_test.go]: Done.

File: internal/services/engines/jvm/rules.go [hunk 2]
```diff
@@ -459,10 +459,10 @@ func NewBase64Decode() *text.Rule {
 			Severity:    severities.Low.ToString(),
 			Confidence:  confidence.Low.ToString(),
 		},
-		Type: text.AndMatch,
+		Type: text.OrMatch,
 		Expressions: []*regexp.Regexp{
 			regexp.MustCompile(`android.util.Base64`),
-			regexp.MustCompile(`.decode`),
+			regexp.MustCompile(`.decode\(`),
```
Comment (wiliansilvazup) [inline internal/services/engines/jvm/rules.go:465]: maybe you can change to
```suggestion
			regexp.MustCompile(`\.decode\(`),
```
in order not to have too many false positives, maybe it is better to make it very clear that you will need to access the `encode` or `decode` method

File: internal/services/engines/jvm/rules.go [hunk 3]
```diff
@@ -707,8 +707,8 @@ func NewBase64Encode() *text.Rule {
 		Type: text.OrMatch,
 		Expressions: []*regexp.Regexp{
 			regexp.MustCompile(`android.util.Base64`),
-			regexp.MustCompile(`.encodeToString`),
-			regexp.MustCompile(`.encode`),
+			regexp.MustCompile(`.encodeToString\(`),
+			regexp.MustCompile(`.encode\(`),
```
Comment (wiliansilvazup) [inline internal/services/engines/jvm/rules.go:711]:
```suggestion
			regexp.MustCompile(`\.encodeToString\(`),
			regexp.MustCompile(`\.encode\(`),
```

Same here

**Review by wiliansilvazup — CHANGES_REQUESTED** [review]

File: internal/services/engines/jvm/rules.go (hunk 2 above)
Comment (matheusalcantarazup) [reply internal/services/engines/jvm/rules.go]: Done.

File: internal/services/engines/jvm/rules.go (hunk 3 above)
Comment (matheusalcantarazup) [reply internal/services/engines/jvm/rules.go]: Done.

File: internal/services/engines/jvm/samples_test.go [hunk 4]
```diff
@@ -13,3 +13,53 @@
...
+
+const (
+	SampleSafeHSJVM38 = `
+class T {
+	void f() {
+		obj.addContentType("application/x-www-form-urlencoded")
+	}
+}
+	`
+	SampleSafeHSJVM382 = `
```
Comment (nathanmartinszup) [inline internal/services/engines/jvm/samples_test.go:47]: Change it to `Sample2SafeHSJVM38` to be more readable

Comment (matheusalcantarazup) [reply internal/services/engines/jvm/samples_test.go]: Fixed.

**Review by nathanmartinszup — APPROVED** [review]

**Review by iancardosozup — APPROVED** [review]

**Review by wiliansilvazup — APPROVED** [review]
